force-app/main/default/objects/Learn_A__c/Learn_A__c.object-meta.xml
<CustomObject>
    <label>Learn A</label>
    <nameField>
        <label>Learn A Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learn As</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Learn_A__c/fields/Learn_C__c.field-meta.xml
<CustomField>
    <fullName>Learn_C__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Learn C</label>
    <referenceTo>Learn_C__c</referenceTo>
    <relationshipLabel>Learn As</relationshipLabel>
    <relationshipName>Learn_As</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Learn_A__c/fields/Multi_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Multi_Picklist__c</fullName>
    <label>Multi Picklist</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pick X</fullName>
            </value>
            <value>
                <fullName>Pick Y</fullName>
            </value>
            <value>
                <fullName>Pick Z</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Learn_A__c/fields/Picklist__c.field-meta.xml
<CustomField>
    <fullName>Picklist__c</fullName>
    <label>Picklist</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pick A</fullName>
                <default>true</default>
                <label>Pick A</label>
            </value>
            <value>
                <fullName>Pick B</fullName>
            </value>
            <value>
                <fullName>Pick C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Learn_A__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <defaultValue>now()</defaultValue>
    <label>Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Learn_C__c/Learn_C__c.object-meta.xml
<CustomObject>
    <label>Learn C</label>
    <nameField>
        <label>Learn C Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learn Cs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LearnAController.cls
public with sharing class LearnAController {

    // public enum LearnAField {
    //     Name = 'da'
    // }

    @AuraEnabled(cacheable = true)
    public static Map<String, Object> searchLearnAMultiParam(Map<String, Object> searchParams) {
        String searchQuery = 'SELECT Id, Name, Learn_C__r.Name FROM Learn_A__c';
        Boolean looseMatchMultiPicklist = (Boolean) searchParams.get('Loose_Match_Multi_Picklist__c');
        List<String> conditions = new List<String>();
        List<String> conditionKeys = new List<String>{'Name', 'Phone_Number__c', 'Is_Checked__c', 'Start_Time__c', 'End_Time__c', 'Picklist__c', 'Multi_Picklist__c', 'Learn_C__c'};

        for(String key: conditionKeys) {
            Object value = searchParams.get(key);
            if(value != null) addToCondition(conditions, key, value, looseMatchMultiPicklist);
        }

        if(!conditions.isEmpty()) searchQuery += ' WHERE ' + String.join(conditions, ' AND ');

        System.debug(searchQuery);
        List<Learn_A__c> result = Database.query(searchQuery);
        // return 'Query = ' + searchQuery + '\n , Result = ' + result;

        Map<String, Object> resultWithLogs = new Map<String, Object>();
        resultWithLogs.put('result', result);
        resultWithLogs.put('searchQuery', searchQuery);

        return resultWithLogs;
    }

    // Helper functions ...
    private static void addToCondition(List<String> conditions, String key, Object value, Boolean looseMatchMultiPicklist) {
        String condition = '';
        String escapedValue = String.escapeSingleQuotes(value.toString());
        if(key == 'Start_Time__c') condition = 'Time__c >= ' + escapedValue;
        else if(key == 'End_Time__c') condition = 'Time__c <= ' + escapedValue;
        else if(key == 'Picklist__c' || key == 'Learn_C__c') condition = key + listToStringWithOperator((List<Object>) value);
        else if(key == 'Multi_Picklist__c') {
            if(looseMatchMultiPicklist) condition = key + listToStringWithOperator((List<Object>) value);
            else condition = key + ' = ' + listToStringMultiPicklist((List<Object>) value);
        }
        else if(key == 'Name' || key == 'Phone_Number__c') condition = key + ' LIKE \'%' + escapedValue + '%\'';
        else condition = key + ' = ' + escapedValue;

        conditions.add(condition);
    }

    private static String listToStringWithOperator(List<Object> l) {
        List<String> lFinal = new List<String>();
        for(Object s: l) { 
            String cur = String.escapeSingleQuotes(s.toString());
            if(cur != 'NULL') cur = '\'' + cur + '\'';
            lFinal.add(cur);
        }
        String operator = (lFinal.isEmpty())? ' = null': ' in ';
        String operand = (lFinal.isEmpty())? '': ('(' + String.join(lFinal, ', ') + ')');
        return operator + operand;
    }

    private static String listToStringMultiPicklist(List<Object> l) {
        List<String> lFinal = new List<String>();
        for(Object s: l) lFinal.add(String.escapeSingleQuotes(s.toString()));
        lFinal.sort();
        return '\'' + String.join(lFinal, ';') + '\'';
    }
}